### ISSUE TITLE
`pairs` and `ipairs` do not do argument checking

### ISSUE THREAD

**Issue by fatboychummy** [cc-tweaked/Cobalt#87]
When passing a non-table value to either `pairs` or `ipairs`, you will get an occasionally lineless error stating `attempt to index <x> value`, instead of `filename:line: bad argument #1 to ipairs (table expected, got <x>)`

<details><summary>eval.tweaked.cc (1.110.2) vs vanilla lua 5.2 output</summary>

![image](https://github.com/cc-tweaked/Cobalt/assets/39929480/727befe0-bfc6-4e1e-87f8-b961815085fe)

```lua
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> ipairs(nil)
stdin:1: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        stdin:1: in main chunk
        [C]: in ?
> pairs(nil)
stdin:1: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        stdin:1: in main chunk
        [C]: in ?
> next(nil)
stdin:1: bad argument #1 to 'next' (table expected, got nil)
stack traceback:
        [C]: in function 'next'
        stdin:1: in main chunk
        [C]: in ?
```

</details>

<details><summary>pcall catching the line number while running it normally does not</summary>

Code used:
```lua
local function doot()
  for _ in ipairs(nil) do end
end

print(pcall(doot))
for _ in ipairs(nil) do end
```

![image](https://github.com/cc-tweaked/Cobalt/assets/39929480/ced1d7a6-d314-4b47-911d-302fd074d946)

</details>

### Versions tested:
- `eval.tweaked.cc` on CC 1.110.2
- MC 1.20.1, Forge 47.2.23, CC:T 1.110.2

**Comment by SquidDev** [comment]
Thanks for the report! So there's two issues here:

 - The argument validation (or lack of) in `ipairs`: CC is copying Lua 5.3/5.4's behaviour here. `ipairs` now just returns the iterator (and starting index), and relies on the iterator function erroring.
 - The lack of source information is a silly bug in Cobalt, which is fixed by https://github.com/cc-tweaked/Cobalt/commit/e9f6a37a8f2c1db3f0c56d402eea69c9a20b4384 (and https://github.com/cc-tweaked/CC-Tweaked/commit/95be0a25bf23402d38e9f4e95f548611dd6707f6) on the CC:T side. It only occurs on the first frame in a coroutine, hence it not occurring inside `pcall`.
